#!/usr/bin/env bash
# Summary: Show the current docker machine

set -e
[ -n "$DMENV_DEBUG" ] && set -x

if [ -z "$DMENV_MACHINE" ]; then
  DMENV_MACHINE="$(dmenv-machine-name)"
fi

if [ -z "$DMENV_MACHINE" ] || [ "$DMENV_MACHINE" = "system" ]; then
  echo "system"
  exit
fi

machine_active() {
  local machine="$1"
  local active="$(docker-machine active 2>&1)"
  [ "${active}" == "${machine}" ]
}

machine_activate() {
  local machine="$1"
  eval $(docker-machine env ${machine})
}

if machine_active "$DMENV_MACHINE"; then
  echo "$DMENV_MACHINE"
  exit 0
elif machine_activate "$DMENV_MACHINE"; then
  echo "$DMENV_MACHINE"
  exit 0
else
  echo "dmenv: machine \`$DMENV_MACHINE' is not active" >&2
  exit 1
fi
