#!/usr/bin/env bash
#
# Summary: Set or show the shell-specific docker machine
#
# Usage: dmenv shell <machine>
#        dmenv shell --unset
#
# Sets a shell-specific docker machine by setting the `DMENV_MACHINE'
# environment variable in your shell. This machine overrides local
# application-specific machines and the global macine.
#
# <machine> should be a string matching an installed docker machine known to dmenv.
# The special machine string `system' will use your default machine.
# Run `dmenv machine' for a list of available Node machines.

set -e
[ -n "$DMENV_DEBUG" ] && set -x

# Provide dmenv completions
if [ "$1" = "--complete" ]; then
  echo --unset
  echo system
  exec dmenv-machines --bare
fi

machine="$1"

if [ -z "$machine" ]; then
  if [ -z "$DMENV_MACHINE" ]; then
    echo "dmenv: no shell-specific machine configured" >&2
    exit 1
  else
    echo "echo \"\$DMENV_MACHINE\""
    exit
  fi
fi

if [ "$machine" = "--unset" ]; then
  echo "unset DMENV_MACHINE"
  exit
fi

# Make sure the specified machine is installed.
if dmenv-prefix "$machine" >/dev/null; then
  echo "export DMENV_MACHINE=\"${machine}\""
else
  echo "return 1"
  exit 1
fi
