#!/usr/bin/env bash
# Summary: Create a new docker machine

set -e
[ -n "$DMENV_DEBUG" ] && set -x

DMENV_MACHINE="$1"

if [ -z "$DMENV_MACHINE" ]; then
  DMENV_MACHINE="$(dmenv-machine-name)"
fi

if [ -z "$DMENV_MACHINE" ] || [ "$DMENV_MACHINE" = "system" ]; then
  echo "no machine specified"
  exit
fi

machine_create() {
  local active="$(docker-machine create ${1} --driver=virtualbox 2>&1)"
}

if machine_create "$DMENV_MACHINE"; then
  $(dmenv-machine-file-write .dmenv-machine "$DMENV_MACHINE")
  echo "$DMENV_MACHINE"
  exit 0
else
  echo "dmenv: machine-create \`$DMENV_MACHINE' is not active" >&2
  exit 1
fi
