#!/usr/bin/env bash
# Summary: Show the current docker machine

set -e
[ -n "$DMENV_DEBUG" ] && set -x

if [ -z "$DMENV_MACHINE" ]; then
  DMENV_MACHINE="$(dmenv-machine-name)"
fi

if [ -z "$DMENV_MACHINE" ] || [ "$DMENV_MACHINE" = "system" ]; then
  echo "system"
  exit
fi

machine_exists() {
  local machine="$1"
  local available=($(docker-machine ls -q | tr '\n' ' '))
  [[ ${available[*]} =~ ${machine} ]]
}

if machine_exists "$DMENV_MACHINE"; then
  exit 0
else
  echo "dmenv: machine \`$DMENV_MACHINE' does not exist" >&2
  exit 1
fi
