#!/usr/bin/env bash
# Summary: Show the current docker machine

set -e
[ -n "$DMENV_DEBUG" ] && set -x

if [ -z "$DMENV_MACHINE" ]; then
  DMENV_MACHINE="$(dmenv-machine-name)"
fi

if [ -z "$DMENV_MACHINE" ] || [ "$DMENV_MACHINE" = "system" ]; then
  echo "system"
  exit
fi

machine_running() {
  local machine="$1"
#  local available=($(docker-machine ls -q | tr '\n' ' '))
  local running="$(docker-machine status ${machine} 2>&1)"
  [ "${running}" == "Running" ]
}

if machine_running "$DMENV_MACHINE"; then
  echo "$DMENV_MACHINE"
  exit 0
else
  echo "dmenv: machine \`$DMENV_MACHINE' is not running" >&2
  exit 1
fi
