#!/usr/bin/env bash
# Summary: Show the current docker machine

set -e
[ -n "$DMENV_DEBUG" ] && set -x

if [ -z "$DMENV_MACHINE" ]; then
  DMENV_MACHINE="$(dmenv-machine-name)"
fi

if [ -z "$DMENV_MACHINE" ] || [ "$DMENV_MACHINE" = "system" ]; then
  echo "system"
  exit
fi

machine_start() {
  docker-machine start ${1} 2>&1
}

if dmenv-machine-running "$DMENV_MACHINE"; then
    echo "dmenv: machine \`$DMENV_MACHINE' is already started" >&2
    exit 0
else
    if machine_start "$DMENV_MACHINE"; then
        docker-machine regenerate-certs --force "$DMENV_MACHINE"
        exit 0
    else
        echo "dmenv: machine \`$DMENV_MACHINE' is not started" >&2
        exit 1
    fi
fi