#!/usr/bin/env bash
# Summary: Show the current docker machine

set -e
[ -n "$DMENV_DEBUG" ] && set -x

if [ -z "$DMENV_MACHINE" ]; then
  DMENV_MACHINE_FILE="$(dmenv-machine-file)"
  DMENV_MACHINE="$(dmenv-machine-file-read "$DMENV_MACHINE_FILE" || true)"
fi

if [ -z "$DMENV_MACHINE" ] || [ "$DMENV_MACHINE" = "system" ]; then
  echo "system"
  exit
fi

echo "$DMENV_MACHINE"
