#!/usr/bin/env bash
# Summary: Stop the docker machine by name

set -e
[ -n "$DMENV_DEBUG" ] && set -x

if [ -z "$DMENV_MACHINE" ]; then
  DMENV_MACHINE="$(dmenv-machine-name)"
fi

if [ -z "$DMENV_MACHINE" ] || [ "$DMENV_MACHINE" = "system" ]; then
  echo "system"
  exit
fi

machine_stop() {
  docker-machine stop ${1} 2>&1
}

if dmenv-machine-running "$DMENV_MACHINE"; then
    if machine_stop "$DMENV_MACHINE"; then
        exit 0
    else
        echo "dmenv: machine \`$DMENV_MACHINE' is not stopped" >&2
        exit 1
    fi
else
    exit 0
fi