#!/usr/bin/env bash
# Summary: Create a new docker machine

set -e
[ -n "$DMENV_DEBUG" ] && set -x

DMENV_MACHINE="$1"

if [ -z "$DMENV_MACHINE" ]; then
  DMENV_MACHINE="$(dmenv-machine-name)"
fi

if [ -z "$DMENV_MACHINE" ] || [ "$DMENV_MACHINE" = "system" ]; then
  echo "no machine specified"
  exit
fi

machine_active() {
  local machine="$1"
  local active="$(docker-machine active 2>&1)"
  [ "${active}" == "${machine}" ]
}

if machine_active "$DMENV_MACHINE"; then
    echo "dmenv: activate \`$DMENV_MACHINE' already active" >&2
    exit 0
else
    if dmenv-start "$DMENV_MACHINE"; then
#        docker-machine regenerate-certs --force "$DMENV_MACHINE"
        eval "$(docker-machine env ${DMENV_MACHINE})"
        echo "dmenv: activate \`$DMENV_MACHINE' activated" >&2
        exit 0
    else
        echo "dmenv: activate \`$DMENV_MACHINE' not activated" >&2
        exit 1
    fi
fi