#!/usr/bin/env bash

set -e
[ -n "$DMENV_DEBUG" ] && set -x

resolve_link() {
  $(type -p greadlink readlink | head -1) "$1"
}

abs_dirname() {
  local cwd="$(pwd)"
  local path="$1"

  while [ -n "$path" ]; do
    cd "${path%/*}"
    local name="${path##*/}"
    path="$(resolve_link "$name" || true)"
  done

  pwd
  cd "$cwd"
}

if [ -z "${DMENV_ROOT}" ]; then
  DMENV_ROOT="${HOME}/.dmenv"
else
  DMENV_ROOT="${DMENV_ROOT%/}"
fi
export DMENV_ROOT

if [ -z "${DMENV_DIR}" ]; then
  DMENV_DIR="$(pwd)"
else
  cd "$DMENV_DIR" 2>/dev/null || {
    echo "dmenv: cannot change working directory to \`$DMENV_DIR'"
    exit 1
  } >&2
  DMENV_DIR="$(pwd)"
  cd "$OLDPWD"
fi
export DMENV_DIR


shopt -s nullglob

bin_path="$(abs_dirname "$0")"
for plugin_bin in "${DMENV_ROOT}/plugins/"*/bin; do
  bin_path="${bin_path}:${plugin_bin}"
done
export PATH="${bin_path}:${PATH}"

hook_path="${DMENV_HOOK_PATH}:${DMENV_ROOT}/dmenv.d:/usr/local/etc/dmenv.d:/etc/dmenv.d:/usr/lib/dmenv/hooks"
for plugin_hook in "${DMENV_ROOT}/plugins/"*/etc/dmenv.d; do
  hook_path="${hook_path}:${plugin_hook}"
done
export DMENV_HOOK_PATH="$hook_path"

shopt -u nullglob


command="$1"
case "$command" in
"" | "-h" | "--help" )
  echo -e "$(dmenv---version)\n$(dmenv-help)" >&2
  ;;
"-v" )
  exec dmenv---version
  ;;
* )
  command_path="$(command -v "dmenv-$command" || true)"
  if [ -z "$command_path" ]; then
    echo "dmenv: no such command \`$command'" >&2
    exit 1
  fi

  shift 1
  exec "$command_path" "$@"
  ;;
esac
