#!/usr/bin/env bash

set -e
[ -n "$DMENV_DEBUG" ] && set -x

# Provide dmenv completions
if [ "$1" = "--complete" ]; then
  exec dmenv-rehash --complete
fi

# When dmenv shell integration is enabled, delegate to dmenv-rehash,
# then tell the shell to empty its command lookup cache.
dmenv-rehash
echo "hash -r"
