#!/usr/bin/env bash
# Summary: Display prefix for a docker machine
# Usage: dmenv prefix [<machine>]
#
# Displays the directory where a docker machine is installed. If no
# machine is given, `dmenv prefix' displays the location of the
# currently selected machine.

set -e
[ -n "$DMENV_DEBUG" ] && set -x

# Provide dmenv completions
if [ "$1" = "--complete" ]; then
  echo system
  exec dmenv-machines --bare
fi

if [ -n "$1" ]; then
  export DMENV_MACHINE="$1"
elif [ -z "$DMENV_MACHINE" ]; then
  DMENV_MACHINE="$(dmenv-machine-name)"
fi

#if [ "$DMENV_MACHINE" = "system" ]; then
#  NODE_PATH="$(dmenv-which node)"
#  NODE_PATH="${NODE_PATH%/*}"
#  echo "${NODE_PATH%/bin}"
#  exit
#fi

DMENV_PREFIX_PATH="${DMENV_ROOT}/machines/${DMENV_MACHINE}"
if [ ! -d "$DMENV_PREFIX_PATH" ]; then
  echo "dmenv: machine \`${DMENV_MACHINE}' not installed" >&2
  exit 1
fi

echo "$DMENV_PREFIX_PATH"
