#!/usr/bin/env bash
# Summary: Start the docker machine by name

set -e
[ -n "$DMENV_DEBUG" ] && set -x

if [ -z "$DMENV_MACHINE" ]; then
  DMENV_MACHINE="$(dmenv-machine-name)"
fi

if [ -z "$DMENV_MACHINE" ] || [ "$DMENV_MACHINE" = "system" ]; then
  echo "system"
  exit
fi

machine_running() {
  local machine="$1"
  local running="$(docker-machine status ${machine} 2>&1)"
  [ "${running}" == "Running" ]
}

machine_start() {
  docker-machine start ${1} 2>&1
}

if machine_running "$DMENV_MACHINE"; then
    echo "dmenv: machine \`$DMENV_MACHINE' already running" >&2
    exit 0
else
    if machine_start "$DMENV_MACHINE"; then
        docker-machine regenerate-certs --force "$DMENV_MACHINE"
        echo "dmenv: machine \`$DMENV_MACHINE' started" >&2
        exit 0
    else
        echo "dmenv: machine \`$DMENV_MACHINE' is not started" >&2
        exit 1
    fi
fi