#!/usr/bin/env bash
# Summary: Stop the docker machine by name

set -e
[ -n "$DMENV_DEBUG" ] && set -x

if [ -z "$DMENV_MACHINE" ]; then
  DMENV_MACHINE="$(dmenv-machine-name)"
fi

if [ -z "$DMENV_MACHINE" ] || [ "$DMENV_MACHINE" = "system" ]; then
  echo "system"
  exit
fi

machine_running() {
  local machine="$1"
  local running="$(docker-machine status ${machine} 2>&1)"
  [ "${running}" == "Running" ]
}

machine_stop() {
  docker-machine stop ${1} 2>&1
}

if machine_running "$DMENV_MACHINE"; then
    if machine_stop "$DMENV_MACHINE"; then
        echo "dmenv: machine \`$DMENV_MACHINE' stopped" >&2
        exit 0
    else
        echo "dmenv: machine \`$DMENV_MACHINE' not stopped" >&2
        exit 1
    fi
else
    echo "dmenv: machine \`$DMENV_MACHINE' not running" >&2
    exit 0
fi